Including option for both storage and transmission losses in the ESR
GenXProject/GenX pull request #351
Opened 2023-02-10 19:09 UTC by sambuddhac

This PR attempts to include the transmission losses along with the storage round trip losses as part of ESR by introducing the switch `include_transmission_losses_in_esr` and adding some extra lines at the end of `transmission.jl`

2023-02-10 21:12 UTC, JesseJenkins requested changes
Change settings flag to `IncludeLossesInESR`
Account for time weights in weighted sum of loss requirements (see how storage losses and demand are treated in ESR cosntraint for example).

2023-02-10 21:16 UTC, JesseJenkins requested changes
Also:
-Remove settings flag from equation and use in if statements
-Ensure the storage loss is triggered by same IncludeLossesInESR settings flag in storage.jl

2023-03-08 17:43 UTC, sambuddhac commented
This is now ready for review (and approval, if everything looks correct) @JesseJenkins @dharik13 . Please let me know if there is any more errors. Thanks !!!

2023-03-15 04:11 UTC, RuaridhMacd approved these changes
This looks correct to me.

Two issues, which may not need to be in this PR:
- [x] Has the documentation been updated to include the new formula and options?
- [ ] Does this affect anything in write_esr_prices.jl and write_esr_revenue.jl?

2023-03-21 02:37 UTC, JesseJenkins commented
@sambuddhac how are losses on specific transmission lines applied to specific ESR constraints that cover different zones? 

I think this change sums losses from _all_  lines and adds them to each ESR constraint. 

`@expression(EP, eESRTran[ESR=1:inputs["nESR"]], sum(inputs["dfESR"][z,ESR]*sum(EP[:eTLOSS][l,t] for l in LOSS_LINES) for z=findall(x->x>0,inputs["dfESR"][:,ESR])))
`
But there can be multiple ESR regions that containt subsets of all zones. So including losses from transmission lines actually gets a little more complicated than the storage losses. Storage resources are assigned to a specific zone. A transmission line might link two regions that are part of the same ESR or it might link two that are not part of the same ESR. So I think we need to assign 1/2 of the losses from each line to the constraint for any ESR region that includes the start node for that line and the other 1/2 to any ESR region that includes the end node? That should work to apply 100% of the losses from a line that begins and ends in two zones belonging to the same ESR region and split the losses half and half between start and end zones that belong to different ESR regions (or where one of the zones is not part of an ESR region). I think you can accomplish that by summing across all lines in LOSS_LINES and where the start nodes of those lines are contained in the set of zones in the ESR region and then subtracting 1/2 of this sum to the ESR balance constraint; and then do the same thing but summing losses for lines where the end nodes of those lines are contained in the set of zones in the ESR region. This mirrors how line losses are included in the power balance constraints for each zone, so please review that for inspiration.

2023-04-13 18:32 UTC, sambuddhac commented
@JesseJenkins , @cfe316 , this PR is now updated and should have the correct formulations.

2023-04-13 21:47 UTC, JesseJenkins commented
@sambuddhac this doesnt look right.

We have no defined: 

`@expression(EP, eLosses_By_Zone[z=1:Z,t=1:T], sum(abs(inputs["pNet_Map"][l,z]) * (1/2) *vTLOSS[l,t] for l in LOSS_LINES))`

Then later you have added:

	`@expression(EP, eTLOSS_By_Zone[z=1:Z,t=1:T], sum(abs(inputs["pNet_Map"][y,z])*(1/2) * inputs["omega"][t]*EP[:vTLOSS][y,t] for y in LOSS_LINES))
	# ESR Lossses
	if EnergyShareRequirement >= 1
		if IncludeLossesInESR == 1
			@expression(EP, eESRTran[ESR=1:inputs["nESR"]], sum(inputs["dfESR"][z,ESR]*sum(EP[:eTLOSS_By_Zone][z,t] for t in 1:T) for z=findall(x->x>0,inputs["dfESR"][:,ESR])))
			EP[:eESR] -= eESRTran
		end
	end'
	
Since 'eLosses_By_Zone' is already defined for each zone and each time period, all you need to add losses to the energy share requirement is to sum across this expression. As in:

	'if EnergyShareRequirement >= 1
		if IncludeLossesInESR == 1
			@expression(EP, eESRTran[ESR=1:inputs["nESR"]], sum(inputs["dfESR"][z,ESR]*sum(inputs["omega"][t]*EP[:eLosses_By_Zone][z,t] for t in 1:T) for z=findall(x->x>0,inputs["dfESR"][:,ESR])))
			EP[:eESR] -= eESRTran
		end
	end'

Right?

2023-04-14 14:22 UTC, sambuddhac commented
I am sorry for the mistake and thanks for pointing, @JesseJenkins . Just corrected !!!

2023-04-14 20:45 UTC, JesseJenkins approved these changes

2023-04-14 21:27 UTC, merged