Inclusion of Reserve and Regulation in ramp limits
GenXProject/GenX pull request #352
Opened 2023-02-10 19:43 UTC by sambuddhac

This PR attempts to correct the ramping constraints for thermal and hydro generators by introducing the reserve and regulation terms in the respective constraints and by changing 

	```
@constraint(EP,[y in THERM_COMMIT, t in 1:T],
		EP[:vP][y,t]-EP[:vP][y, hoursbefore(p, t, 1)] <= dfGen[y,:Ramp_Up_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
			+ min(inputs["pP_Max"][y,t],max(dfGen[y,:Min_Power],dfGen[y,:Ramp_Up_Percentage]))*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
			- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSHUT][y,t])

		# rampdown constraints
	@constraint(EP,[y in THERM_COMMIT, t in 1:T],
		EP[:vP][y, hoursbefore(p, t, 1)]-EP[:vP][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
			- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
			+ min(inputs["pP_Max"][y,t],max(dfGen[y,:Min_Power],dfGen[y,:Ramp_Dn_Percentage]))*dfGen[y,:Cap_Size]*EP[:vSHUT][y,t])
```

to 

	```
@constraint(EP,[y in THERM_COMMIT, t in 1:T],
		EP[:vP][y,t]+EP[:vREG][y,t]+EP[:vRSV][y,t]-EP[:vP][y, hoursbefore(p, t, 1)]-EP[:vREG][y,hoursbefore(p, t, 1)]-EP[:vRSV][y,hoursbefore(p, t, 1)] <= dfGen[y,:Ramp_Up_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
			+ min(inputs["pP_Max"][y,t],max(dfGen[y,:Min_Power],dfGen[y,:Ramp_Up_Percentage]))*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
			- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSHUT][y,t])

		# rampdown constraints
	@constraint(EP,[y in THERM_COMMIT, t in 1:T],
		EP[:vP][y, hoursbefore(p, t, 1)]+EP[:vREG][y,hoursbefore(p, t, 1)]+EP[:vRSV][y,hoursbefore(p, t, 1)]-EP[:vP][y,t]-EP[:vREG][y,t]-EP[:vRSV][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
			- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
			+ min(inputs["pP_Max"][y,t],max(dfGen[y,:Min_Power],dfGen[y,:Ramp_Dn_Percentage]))*dfGen[y,:Cap_Size]*EP[:vSHUT][y,t])
```

2023-02-10 21:25 UTC, JesseJenkins requested changes
Worst case ramp up would be going from REG down in one period to providing REG up and RSV up in the next period, so write as:

cRampUp[y in HYDRO_RES, t in 1:T], EP[:vP][y,t]+ EP[:vREG][y,t]+EP[:vRSV][y,t] - EP[:vP][y, hoursbefore(p,t,1)]-EP[:vREG][y, hoursbefore(p,t,1)] <= dfGen[y,:Ramp_Up_Percentage]*EP[:eTotalCap][y]

Conversly, worst case ramp down would be going from RSV up and REG up in one period to providing REG down in the next period, so write as:

cRampDown[y in HYDRO_RES, t in 1:T], EP[:vP][y, hoursbefore(p,t,1)] + EP[:vREG][y, hoursbefore(p,t,1)] - EP[:vP][y,t] - EP[:vREG][y,t] - EP[:vRSV][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*EP[:eTotalCap][y]

@Sam please revise code and also update documentation with this formulation and the above explanation of changes to ramp constraints when modeling reserves.

2023-03-06 22:48 UTC, sambuddhac commented
This is now ready for review (and approval, if everything looks correct) @JesseJenkins . Please let me know if there is any more errors. Thanks !!!

2023-03-21 02:18 UTC, JesseJenkins commented
Sorry @sambuddhac I made a mistake when writing the ramp down constraint above (described it correctly in the sentence but not in the psuedocode. Ramp down should be:

Worst case ramp down would be going from RSV up and REG up in one period to providing REG down in the next period, which is:

cRampDown[y in [HYDRO_RES or THERM_COMMIT], t in 1:T], EP[:vP][y, hoursbefore(p,t,1)] + EP[:vREG][y, hoursbefore(p,t,1)] + EP[:vRSV][y, hoursbefore(p,t,1)] - EP[:vP][y,t] - EP[:vREG][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*EP[:eTotalCap][y]

You faithfully implemented my erroneous ramp down constraint formulation. Please update to the above and fix documentation for ramp down constraints for hydro and thermal units. Thanks.

2023-03-27 03:39 UTC, sambuddhac commented
> Sorry @sambuddhac I made a mistake when writing the ramp down constraint above (described it correctly in the sentence but not in the psuedocode. Ramp down should be:
> 
> Worst case ramp down would be going from RSV up and REG up in one period to providing REG down in the next period, which is:
> 
> cRampDown[y in [HYDRO_RES or THERM_COMMIT], t in 1:T], EP[:vP][y, hoursbefore(p,t,1)] + EP[:vREG][y, hoursbefore(p,t,1)] + EP[:vRSV][y, hoursbefore(p,t,1)] - EP[:vP][y,t] - EP[:vREG][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*EP[:eTotalCap][y]
> 
> You faithfully implemented my erroneous ramp down constraint formulation. Please update to the above and fix documentation for ramp down constraints for hydro and thermal units. Thanks.

Thanks @JesseJenkins !!! I understand it now and fixed it.

2023-03-29 17:28 UTC, JesseJenkins approved these changes

2023-03-29 17:29 UTC, JesseJenkins commented
@sambuddhac I've approved this change but you also need to update the documentation to ensure the formulation described there is accurate and consistent with the final formulation above. Please do so before pushing this to Main. Thank you.

2023-04-13 18:33 UTC, merged