Inclusion of Max Cap Requirement
GenXProject/GenX pull request #365
Opened 2023-02-27 19:49 UTC by sambuddhac

This PR attempts to take into account the Max Capacity constraint in addition to the min cap constraint

2023-02-27 19:50 UTC, sambuddhac commented
Draft PR in the process. Will change the status once I finalize the PR and let all know.

2023-02-28 15:23 UTC, cfe316 requested changes
Hi Sam,

Thanks for making this PR and tagging me as a reviewer.
This doesn't look like a complete feature. If I search for MinCapReq and MinCapRes I see that they're in all these files, so more changed will be necessary. I suppose in principle the rest of the changes could be made later.

```
write_outputs/write_outputs.jl
write_outputs/minimum_capacity_requirement/write_minimum_capacity_requirement.jl
write_outputs/write_subsidy_revenue.jl
write_outputs/write_net_revenue.jl
configure_settings/configure_settings.jl
model/generate_model.jl
model/core/discharge/investment_discharge.jl
model/policies/minimum_capacity_requirement.jl
load_inputs/load_inputs.jl
load_inputs/load_minimum_capacity_requirement.jl
```
I'm also not certain that this will work, technically, since line 191 adds to an expression which does not already exist.

As a stylistic matter, `:][!, R_ID]` should be shortened to `:R_ID]`.

2023-02-28 15:27 UTC, cfe316 commented
Ah, sorry, I hadn't seen that this was a draft PR.

2023-02-28 20:32 UTC, sambuddhac commented
@cfe316 I will finish this and then finalize the PR. Will let y'all know.

2023-03-03 19:19 UTC, cfe316 commented
`MinCapReq` is mentioned in `write_net_revenue.jl`. Does this needs to be addressed in some similar way?

2023-03-03 21:21 UTC, JesseJenkins commented
> `MinCapReq` is mentioned in `write_net_revenue.jl`. Does this needs to be addressed in some similar way?

No, this is not necessary for max cap constraint. MinCapReq shows up in the revenues because we want to know the subsidy required (additional revenue) to make generators/resources whole at that constraint level.

2023-03-08 22:21 UTC, sambuddhac commented
This is now ready for review. @cfe316 @JesseJenkins @dharik13 , please let me know if there needs to be further modifications or if everything looks alright, then if it can be merged with `Develop`

2023-03-09 15:13 UTC, cfe316 approved these changes

2023-03-14 20:14 UTC, cfe316 approved these changes

2023-03-14 20:14 UTC, cfe316 commented on src/write_outputs/write_outputs.jl
> +			dfMinCapReq = write_maximum_capacity_requirement(path, inputs, setup, EP)
This dataframe should be called dfMaxCapReq.

2023-03-14 20:30 UTC, merged