Feature electrolysis basic
GenXProject/GenX pull request #525
Opened 2023-08-15 21:25 UTC by JesseJenkins

This feature implements a basic electrolyzer resource. 

The user either specifies a minimum quantity of hydrogen that must be produced annually by each electrolyzer and/or a price per metric tonne of hydrogen which is subtracted from the objective function. 

This implementation features hourly ramp up/down constraints and minimum and maximum hourly power consumption constraints (similar to constraints for thermal generators without unit commitment). 

It also features an hourly clean supply matching constraint that enables implementation of the 'three pillars' requirements for clean hydrogen sourcing of 'new supply/additionality', 'deliverability' and 'temporal matching.'

Demand from electrolyzers can also be added to Energy Resource Standard constraints to ensure that clean supply for electrolysis is not counted towards RPS/CES goals. 

Documentation should be complete, but please review for clarity before approval.

2023-08-15 22:36 UTC, gmantegna requested changes
Looks good in terms of the constraints and test case. My one major concern is that it introduces requirements for new columns in Generators_data.csv, meaning it is not backwards compatible (also I think @cfe316 has mentioned we want to move towards reducing requirements for what is in Generators_data which makes sense). Is it possible to refactor so that this is not necessary? This could probably be accomplished similar to how retrofit resources are handled in load_generators_data. Finally please merge in the latest develop to this branch so that we can sort out any merge conflicts before merging (since this branch is branched from a relatively old commit of main).

2023-08-15 22:48 UTC, gmantegna commented
Oh also, would it be possible to add documentation on the required data inputs to data_documentation.md?

2023-08-16 11:56 UTC, JesseJenkins commented
> Looks good in terms of the constraints and test case. My one major concern is that it introduces requirements for new columns in Generators_data.csv, meaning it is not backwards compatible (also I think @cfe316 has mentioned we want to move towards reducing requirements for what is in Generators_data which makes sense).

Thanks for catching this. My intention was to make all additional electrolyzer related input columns optional and excluded so long as the set of electrolyzer resources established in `load_generators_data.jl` is empty. 

This is handled similar to other resources by skipping over the `electrolyzers()` method call in `generate_model()` if the set of electrolyzer resources is empty. See lines 160-162:

```
if !isempty(inputs["ELECTROLYZER"])
	electrolyzer!(EP, inputs, setup)
end
```

However, I just tested this setup on the OneZone sample system without electrolyzer inputs, and it fails as it tries to read the key `:ELECTROLYZER` from the gen_in dataframe (generators data inputs) at `load_generators_data.jl` line 53 in my most recent commit:

```
#Set of hydrogen electolyzer resources
inputs_gen["ELECTROLYZER"] = gen_in[gen_in.ELECTROLYZER.>=1,:R_ID]
```

The fix for this in my latest commit is to wrap the creation of the `ELECTROLYZER` set as follows:

```
# Set of hydrogen electolyzer resources (optional set):
if ("ELECTROLYZER" in names(gen_in))
	inputs_gen["ELECTROLYZER"] = gen_in[gen_in.ELECTROLYZER.>=1,:R_ID]
else
	inputs_gen["ELECTROLYZER"] = Vector()
end
```

This creates an empty Vector if the `:ELECTROLYZER` key is not present in generators data inputs DataFrame `gen_in`. This should probably be a standard practice for adding a new resource feature while maintaining backwards compatability.

Note that I also missed a couple of spots in write outputs functions that were not skipping over electrolyzer related outputs when the `ELECTROLYZER` set was empty. Those are not fixed as well. 

This now runs for the OneZone test system without electrolyzer related inputs, so I think this is now backwards compatable. Please confirm @gmantegna.

2023-08-16 12:27 UTC, JesseJenkins commented
> Oh also, would it be possible to add documentation on the required data inputs to data_documentation.md?

This is complete in the latest commit, as well as inclusion of all electrolyzer related parameters and sets in the notation.md file.

2023-08-16 12:27 UTC, JesseJenkins commented
@gmantegna or @cfe316 can one of you write an appropriate entry to the CHANGELOG as well to documentation this feature addition. I'm unsure on the appropriate style for those changes.

2023-08-16 13:29 UTC, cfe316 commented
That's fine, we should be able to push to this branch just fine.On Aug 16, 2023 8:28 AM, Jesse Jenkins ***@***.***> wrote:
@gmantegna or @cfe316 can one of you write an appropriate entry to the CHANGELOG as well to documentation this feature addition. I'm unsure on the appropriate style for those changes.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-08-16 14:03 UTC, cfe316 commented
I rebased this branch on the most recent `develop`. (It was an easy rebase).

2023-08-16 16:10 UTC, cfe316 requested changes
This looks good. I had a few minor change requests and went ahead and did them. 

My main question now is on the modification of the ThreeZones example and whether it can be returned to being the same.

2023-08-16 16:18 UTC, cfe316 commented
ELECTROLYZER is mutually exclusive with THERM, STOR, FLEX ... right? It needs to be added to the list of mutually-exclusive resources in order to not throw an error at load time.

2023-08-16 17:42 UTC, cfe316 commented
@JesseJenkins by "Energy Resource Standard" did you mean "Energy Share Requirement" (`:eESR`)? Seen in a few places in comments and documentation.

2023-08-16 18:31 UTC, JesseJenkins commented
Correct.

On Wed, Aug 16, 2023, 12:18 PM Jacob Schwartz ***@***.***>
wrote:

> ELECTROLYZER is mutually exclusive with THERM, STOR, FLEX ... right? It
> needs to be added to the list of mutually-exclusive resources in order to
> not throw an error at load time.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GenXProject/GenX/pull/525#issuecomment-1680907142>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPYTSFXLGSLS2BZYCKMK5TXVTXFRANCNFSM6AAAAAA3RTNF6Q>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-08-16 18:31 UTC, JesseJenkins commented
Correct.

On Wed, Aug 16, 2023, 1:42 PM Jacob Schwartz ***@***.***>
wrote:

> @JesseJenkins <https://github.com/JesseJenkins> by "Energy Resource
> Standard" did you mean "Energy Share Requirement" (:eESR)? Seen in a few
> places in comments and documentation.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GenXProject/GenX/pull/525#issuecomment-1681030012>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACPYTSGSIGCT7BFUQ2CJWCTXVUBBNANCNFSM6AAAAAA3RTNF6Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-16 19:04 UTC, gmantegna approved these changes
Looks good. Thanks for addressing the changes.

2023-08-16 19:10 UTC, cfe316 approved these changes
Looks good now.

2023-08-17 14:37 UTC, cfe316 requested changes
Notes
--------
* consider changing `ELECTROLYZER` column to `SIMPLE_ELECTROLYZER` or similar ("Basic" is too similar to "alkaline"....)
* fix `README.md` in the example case; right now it's the same as for a generic SmallNewEngland example

2023-08-18 21:16 UTC, cfe316 reviewed
> -Question: we want a Three Zone example as well? I think Jacob removed the electrolyzer input tests I had provided for the New England Three Zone system to ensure it works as intended in a multi-zone case.

This is a good idea, but could we have a very-small (one day, few generators) three-zone test case? 

> HydrogenHourylMatching

Is this a typo or intentional to miss Dolphyn?

2023-08-21 13:26 UTC, JesseJenkins commented
'Houryl' was a typo! Thanks @cfe316

2023-08-24 14:47 UTC, dharik13 commented on CHANGELOG.md
Would it help to have an additional description of what the electrolyzer model does?

2023-08-24 15:00 UTC, dharik13 commented on src/load_inputs/load_generators_data.jl
I would suggest keeping the delete comments on start fuel cost parameter scaling since they are non-intuitive.

2023-08-24 18:22 UTC, dharik13 reviewed
Looks good overall. Here are a few suggestions/questions:
- I would suggesting introducing a flag in the model setup to choose which type  time-matching requirement to enforce (annual vs. hourly with excess sales to start but one could easily model others like hourly without excess sales monthly which is relevant for EU for example). Under the time-matching_requirement branch (https://github.com/macroenergy/DOLPHYN/tree/time_matching_requirements) in DOLPHYN, we allow user to choose between one of  three TMRs currently: a) hourly with excess sales allowed, b) hourly with excess sales disallowed and c) annual. Something similar can be readily implemented here.
    - In electrolyzer.jl: By setting alternative values of HydrogenHourlyMatching flag (e.g. 1=Hourly, 2 = hourly with no excess sales, 3 =annual), one can enhance flexibility of the code to test multiple policy constructs.  If this is implemented, it would be more informative to change the flag label to HydrogenTimeMatching or something like that.
- A general comment: if this is meant to be a basic implementation, I would suggest adding a section in the mark up documentation for electrolyzer.jl where the modeled features are highlighted. That would also be a good place to  point them to the availability of a richer implementation in the DOLPHYN code.
- In load_generators_data.jl, I would suggest keeping the deleted comments on start fuel cost units changes with parameter scaling since they are non-intuitive (this comment assumes that this will eventually be pushed to main)
- In electrolyzer.jl:  any reason for enforcing only minimum annual demand but not daily or hourly demand? Using an annual demand might not capture the fact that the electrolyzer would often need to be ovesrized relative to avg. hourly H2 demand.

2023-08-24 22:15 UTC, cfe316 approved these changes
Looks good.

2023-08-24 22:22 UTC, merged